<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $report_title; ?></title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
        }
        .report-header {
            text-align: center;
            margin-bottom: 30px;
        }
        .report-header h1 {
            font-size: 24px;
            margin-bottom: 5px;
        }
        .report-header p {
            margin: 5px 0;
            color: #666;
        }
        .summary-stats {
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
            margin-bottom: 30px;
        }
        .stat-box {
            flex: 1;
            min-width: 200px;
            padding: 15px;
            border-radius: 8px;
            background-color: #f5f5f5;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .stat-box h3 {
            margin-top: 0;
            margin-bottom: 5px;
            font-size: 14px;
            color: #666;
        }
        .stat-box p {
            margin: 0;
            font-size: 20px;
            font-weight: bold;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            page-break-inside: auto;
        }
        tr {
            page-break-inside: avoid;
            page-break-after: auto;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 10px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .status-verified {
            padding: 4px 8px;
            border-radius: 12px;
            font-size: 12px;
            font-weight: bold;
            background-color: #d1fae5;
            color: #065f46;
        }
        .no-print {
            margin-bottom: 20px;
        }
        @media print {
            .no-print {
                display: none;
            }
            body {
                padding: 0;
            }
            thead {
                display: table-header-group;
            }
            tfoot {
                display: table-footer-group;
            }
        }
    </style>
</head>
<body>
    <div class="no-print">
        <button onclick="window.print();" style="padding: 10px 20px; background-color: #4CAF50; color: white; border: none; border-radius: 4px; cursor: pointer; font-size: 16px;">
            Print / Save as PDF
        </button>
        <p>
            <i>Instructions: Click the button above to print this report or save it as a PDF. In the print dialog, select "Save as PDF" as the destination to create a PDF file.</i>
        </p>
        <hr>
    </div>
    
    <div class="report-header">
        <h1>Oblatos Foundation by OSJ</h1>
        <p><?php echo $report_title; ?></p>
        <p>Generated on: <?php echo date('F j, Y, g:i a'); ?></p>
        <p>Generated by: <?php echo htmlspecialchars($_SESSION['full_name'] ?? $_SESSION['name'] ?? 'System User'); ?></p>
    </div>
    
    <div class="summary-stats">
        <div class="stat-box">
            <h3>Total Verified Donations</h3>
            <p><?php echo formatPeso($total_amount); ?></p>
        </div>
        <div class="stat-box">
            <h3>Number of Transactions</h3>
            <p><?php echo $transaction_count; ?></p>
        </div>
        <div class="stat-box">
            <h3>Bank Transfers</h3>
            <p><?php echo $payment_methods['bank_transfer']; ?></p>
        </div>
        <div class="stat-box">
            <h3>GCash Payments</h3>
            <p><?php echo $payment_methods['gcash']; ?></p>
        </div>
    </div>
    
    <h2>Verified Donations List</h2>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Donor</th>
                <th>Amount</th>
                <th>Payment Method</th>
                <th>Reference #</th>
                <th>Verified By</th>
                <th>Verification Date</th>
            </tr>
        </thead>
        <tbody>
            <?php if (count($filtered_donations) > 0): ?>
                <?php foreach ($filtered_donations as $row): ?>
                    <tr>
                        <td><?php echo date('M d, Y', strtotime($row['created_at'] ?? date('Y-m-d'))); ?></td>
                        <td><?php echo htmlspecialchars($row['donor_name'] ?? 'Unknown'); ?></td>
                        <td><?php echo formatPeso($row['amount']); ?></td>
                        <td>
                            <?php 
                            echo isset($row['payment_method']) && strtolower($row['payment_method']) === 'bank_transfer' ? 'Bank Transfer' : 'GCash';
                            ?>
                        </td>
                        <td><?php echo htmlspecialchars($row['reference_number'] ?? 'N/A'); ?></td>
                        <td><?php echo htmlspecialchars($row['verifier_name'] ?? 'N/A'); ?></td>
                        <td><?php echo isset($row['verification_date']) ? date('M d, Y H:i', strtotime($row['verification_date'])) : 'N/A'; ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="7" style="text-align: center;">No verified donations found.</td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>
    
    <script>
        // Auto-suggest printing when the page loads
        window.addEventListener('load', function() {
            // Add a small delay to allow the page to fully render
            setTimeout(function() {
                document.title = "<?php echo $filename; ?>";
            }, 500);
        });
    </script>
</body>
</html> 